"""Maps semantic categories to GL accounts based on chart of accounts."""

from typing import Dict, List, Optional
import logging
import json
from pathlib import Path

logger = logging.getLogger(__name__)


class AccountMapper:
    """Maps semantic categories to General Ledger account codes."""
    
    # Real GL account mapping from Kontoplan.csv
    DEFAULT_CATEGORY_MAPPING = {
        "Raw Materials": [
            "1220 – Materialvorräte",
            "1270 – Angefangene Arbeiten"
        ],
        "Consumables": [
            "1220 – Materialvorräte",
            "1540 – Werkzeuge und Geräte"
        ],
        "Transport": [
            "4061 – Fremdtransporte",
            "4062 – Deponiegebühren"
        ],
        "Pallets": [
            "4010 – Paletten Einkauf",
            "4011 – Paletten Retouren"
        ],
        "Machinery & Equipment": [
            "1500 – Maschinen und Apparate",
            "1540 – Werkzeuge und Geräte"
        ],
        "Vehicles": [
            "1530 – Fahrzeuge",
            "1531 – Lieferwagen"
        ],
        "Buildings & Infrastructure": [
            "1600 – Geschäftsliegenschaften"
        ],
        "IT & Office Equipment": [
            "1521 – Informatik",
            "1520 – Büromaschinen",
            "1510 – Mobiliar und Einrichtungen"
        ],
        "Services": [
            "2004 – Verbindlichkeiten übr. Betriebsaufwand",
            "2000 – Verbindlichkeiten aus L+L"
        ],
        # Legacy mappings for backward compatibility
        "Material": [
            "1220 – Materialvorräte",
            "1270 – Angefangene Arbeiten",
            "1200 – Waren"
        ],
        "Tools": [
            "1540 – Werkzeuge und Geräte",
            "1500 – Maschinen und Apparate",
            "1520 – Büromaschinen"
        ],
        "Service": [
            "2004 – Verbindlichkeiten übr. Betriebsaufwand",
            "2000 – Verbindlichkeiten aus L+L",
            "6000 – External Services"
        ],
        "Surcharge": [
            "2004 – Verbindlichkeiten übr. Betriebsaufwand",
            "4980 – Surcharges & Fees",
            "4900 – Transport & Freight Costs"
        ],
        "Safety": [
            "1220 – Materialvorräte",
            "1540 – Werkzeuge und Geräte",
            "4200 – Consumables"
        ],
        "Operating Supplies": [
            "1220 – Materialvorräte",
            "4200 – Consumables",
            "1540 – Werkzeuge und Geräte"
        ],
        "Other": ["1220 – Materialvorräte"]  # Default fallback
    }
    
    def __init__(self, chart_of_accounts: Optional[Dict[str, List[str]]] = None):
        """Initialize mapper with custom or default chart of accounts.
        
        Args:
            chart_of_accounts: Custom mapping of categories to GL accounts.
                             If None, uses DEFAULT_CATEGORY_MAPPING.
        """
        self.chart_of_accounts = chart_of_accounts or self.DEFAULT_CATEGORY_MAPPING
        # Try to load Pos -> account candidates if present (generated by processing scripts)
        self.pos_mappings = {}
        try:
            pos_file = Path("deliverables/milestone1/pos_mappings.json")
            if pos_file.exists():
                with open(pos_file, "r", encoding="utf-8") as pf:
                    data = json.load(pf)
                    self.pos_mappings = data.get("pos_mappings", {}) or {}
                    logger.info(f"Loaded pos mappings for {len(self.pos_mappings)} positions")
        except Exception:
            # Non-fatal — proceed without Pos data
            logger.debug("No Pos mappings available or failed to read pos_mappings.json")
        logger.info(f"Initialized AccountMapper with {len(self.chart_of_accounts)} categories")
    
    def map_to_accounts(
        self,
        category: str,
        classification_confidence: float,
        invoice_text: str,
        supplier: Optional[str] = None,
        top_k: int = 3,
        pos: Optional[str] = None
    ) -> List[Dict[str, any]]:
        """Map a semantic category to GL account suggestions.
        
        Args:
            category: Semantic category from classifier
            classification_confidence: Confidence score from classification
            invoice_text: Original invoice line item text
            supplier: Optional supplier name for context
            top_k: Number of top suggestions to return (default: 3)
            
        Returns:
            List of account suggestions, each containing:
                - account: GL account code and name
                - confidence: Confidence score for this suggestion
                - explanation: Why this account was suggested
        """
        # Get potential accounts for this category
        potential_accounts = self.chart_of_accounts.get(
            category,
            self.chart_of_accounts.get("Other", ["4200 – Consumables"])
        )
        
        suggestions = []
        
        # If we have Pos-based candidates, build a quick lookup to prioritize them
        pos_priority = {}
        if pos and pos in self.pos_mappings:
            for rank, entry in enumerate(self.pos_mappings[pos].get("candidates", [])):
                # entry contains account_code (code only, e.g., "4010")
                pos_priority[str(entry.get("account_code"))] = {
                    "rank": rank,
                    "avg_confidence": entry.get("avg_confidence", 0.0),
                    "count": entry.get("count", 0)
                }

        for idx, account in enumerate(potential_accounts[:top_k]):
            # Calculate suggestion confidence
            # Primary account gets full classification confidence
            # Alternative accounts get reduced confidence
            # default base confidence
            if idx == 0:
                account_confidence = classification_confidence
                explanation = f"Primary account for category '{category}'"
            else:
                account_confidence = classification_confidence * (0.7 - idx * 0.15)
                explanation = f"Alternative account for category '{category}'"

            # If this account matches a Pos candidate (by code prefix), boost priority
            try:
                acct_code = account.split("–")[0].strip()
            except Exception:
                acct_code = account.split()[0]
            if acct_code in pos_priority:
                # Boost confidence modestly and annotate explanation
                boost = 0.15
                account_confidence = min(1.0, account_confidence + boost)
                explanation += f" (Pos signal: prioritized for Pos {pos})"
            
            # Add context to explanation
            if supplier:
                explanation += f" (Supplier: {supplier})"
            
            suggestions.append({
                "account": account,
                "confidence": round(account_confidence, 3),
                "explanation": explanation
            })
        
        # If we don't have enough suggestions, add fallback
        if len(suggestions) < top_k and category != "Other":
            fallback_accounts = self.chart_of_accounts.get("Other", [])
            for account in fallback_accounts:
                if len(suggestions) >= top_k:
                    break
                if account not in [s["account"] for s in suggestions]:
                    suggestions.append({
                        "account": account,
                        "confidence": round(classification_confidence * 0.3, 3),
                        "explanation": "Fallback account for uncertain classification"
                    })
        
        # Ensure we always have exactly top_k suggestions with unique accounts
        # Gather all available unique accounts from all categories before repeating
        existing_accounts = {s["account"] for s in suggestions}
        
        while len(suggestions) < top_k:
            added = False
            
            # Try to find unique accounts from all categories (prioritize similar ones)
            search_order = [category, "Other", "Material", "Consumables", "Service"]
            for search_category in search_order:
                if added:
                    break
                category_accounts = self.chart_of_accounts.get(search_category, [])
                for account in category_accounts:
                    if account not in existing_accounts:
                        suggestions.append({
                            "account": account,
                            "confidence": round(0.1, 3),
                            "explanation": f"Additional fallback from {search_category} category"
                        })
                        existing_accounts.add(account)
                        added = True
                        break
            
            # If still no unique accounts found after checking all categories, use default fallback
            if not added:
                default_fallback = "1220 – Materialvorräte"
                if default_fallback not in existing_accounts:
                    suggestions.append({
                        "account": default_fallback,
                        "confidence": round(0.05, 3),
                        "explanation": "Default fallback account"
                    })
                    existing_accounts.add(default_fallback)
                else:
                    # Ultimate fallback: if we've truly exhausted everything, break to avoid infinite loop
                    break
        
        # Sort by confidence descending
        suggestions.sort(key=lambda x: x["confidence"], reverse=True)
        
        return suggestions[:top_k]
    
    def update_mapping(self, category: str, accounts: List[str]) -> None:
        """Update the chart of accounts mapping for a category.
        
        Args:
            category: Semantic category to update
            accounts: List of GL account codes to map to this category
        """
        self.chart_of_accounts[category] = accounts
        logger.info(f"Updated mapping for category '{category}' with {len(accounts)} accounts")
    
    def get_all_accounts(self) -> List[str]:
        """Get all GL accounts across all categories.
        
        Returns:
            Flat list of all unique GL account codes
        """
        all_accounts = set()
        for accounts in self.chart_of_accounts.values():
            all_accounts.update(accounts)
        return sorted(list(all_accounts))
    
    def validate_account(self, account: str) -> bool:
        """Check if an account exists in the chart of accounts.
        
        Args:
            account: GL account code to validate
            
        Returns:
            True if account exists, False otherwise
        """
        all_accounts = self.get_all_accounts()
        return account in all_accounts
